### ISSUE TITLE
Some Oneliner python programme

### ISSUE THREAD

**Issue by aman2457** [Anushka-codergirl/Python-Programs#1]
I would like to contribute some online python programs. It would be great if you mark for hacktoberfest.
Kindly look into it @Anushka-codergirl

**Comment by Anushka-codergirl** [comment]
Sorry! This repo isn't created for Hacktoberfest. If you want to contribute, please check [@Anushka-codergirl/Java-Programs](https://github.com/Anushka-codergirl/Java-Programs).
